### ISSUE TITLE
HydroMemo Fails to open

### ISSUE THREAD

**Issue by programmin1** [c7haki/HydroMemo#1]
On Android 2.2.2 I get:

`E/AndroidRuntime(14875): FATAL EXCEPTION: main
E/AndroidRuntime(14875): java.lang.RuntimeException: Unable to start activity ComponentInfo{de.boesling.hydromemo/de.boesling.hydromemo.activities.Preferences}: android.view.InflateException: Binary XML file line #3: Error inflating class SwitchPreference
E/AndroidRuntime(14875):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2663)
E/AndroidRuntime(14875):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2679)
E/AndroidRuntime(14875):    at android.app.ActivityThread.access$2300(ActivityThread.java:125)
E/AndroidRuntime(14875):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2033)
E/AndroidRuntime(14875):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(14875):    at android.os.Looper.loop(Looper.java:123)
E/AndroidRuntime(14875):    at android.app.ActivityThread.main(ActivityThread.java:4627)
E/AndroidRuntime(14875):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(14875):    at java.lang.reflect.Method.invoke(Method.java:521)
E/AndroidRuntime(14875):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
E/AndroidRuntime(14875):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
E/AndroidRuntime(14875):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(14875): Caused by: android.view.InflateException: Binary XML file line #3: Error inflating class SwitchPreference
E/AndroidRuntime(14875):    at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:441)
E/AndroidRuntime(14875):    at android.preference.GenericInflater.rInflate(GenericInflater.java:481)
E/AndroidRuntime(14875):    at android.preference.GenericInflater.inflate(GenericInflater.java:326)
E/AndroidRuntime(14875):    at android.preference.GenericInflater.inflate(GenericInflater.java:263)
E/AndroidRuntime(14875):    at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:251)
E/AndroidRuntime(14875):    at android.preference.PreferenceActivity.addPreferencesFromResource(PreferenceActivity.java:262)
E/AndroidRuntime(14875):    at de.boesling.hydromemo.activities.Preferences.onCreate(Preferences.java:38)
E/AndroidRuntime(14875):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
E/AndroidRuntime(14875):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2627)
E/AndroidRuntime(14875):    ... 11 more
E/AndroidRuntime(14875): Caused by: java.lang.ClassNotFoundException: android.preference.SwitchPreference in loader dalvik.system.PathClassLoader[/data/app/de.boesling.hydromemo-1.apk]
E/AndroidRuntime(14875):    at dalvik.system.PathClassLoader.findClass(PathClassLoader.java:243)
E/AndroidRuntime(14875):    at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
E/AndroidRuntime(14875):    at java.lang.ClassLoader.loadClass(ClassLoader.java:532)
E/AndroidRuntime(14875):    at android.preference.GenericInflater.createItem(GenericInflater.java:375)
E/AndroidRuntime(14875):    at android.preference.GenericInflater.onCreateItem(GenericInflater.java:417)
E/AndroidRuntime(14875):    at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:428)
E/AndroidRuntime(14875):    ... 19 more
W/ActivityManager(25191):   Force finishing activity de.boesling.hydromemo/.activities.Preferences`

**Comment by c7haki** [comment]
fixed
a1263df4c285426693c1dc11c87dc03d9a8e01d6
