### ISSUE TITLE
Higher-quality audio

### ISSUE THREAD

**Issue by ghost** [c7haki/HydroMemo#2]
The present audio clips have quite a bit of noise and utilize a sub-optimal codec. As an example, I have recorded a new 'aaahhh' sample that could be used (just for an example). If you're interested in using it I give it to you, licensed under the CC0 license. 

I would advise usage of the .ogg file format as the quality is quite a bit superior to mp3/m4a. However, here is a .wav in which you are free to do whatever you wish with it.

[link removed]

**Comment by c7haki** [comment]
It seems that the url is already expired :(
Thx for your suggestion. I will give ogg format a try.

**Comment by ghost** [comment]
It works for me - do you have noscript installed? the ABE system will block bit.ly stuff.

Here, I'll include the direct address and remove it later - [link removed]

And ogg isn't really too much of a big deal - I mean, these are cell phones. I just thought there could be a better sound and I can replace the others if you so choose. :)

**Comment by ghost** [comment]
Are you interested in this? Would you like me to give you more samples?

**Comment by c7haki** [comment]
Regarding the quality, you're right. But I don't like the tone of it.
I would like to extend the range of sounds. Do you have some other water sounds?

**Comment by ghost** [comment]
I can make some if you'd like/want to include it.

I'm not sure what you mean by the 'tone' of it - I just made a quick sample that was close to what you had originally used.
